#!/usr/bin/env python3
"""Create zh.json locale by copying ru.json structure and applying Chinese translations."""
import json
from pathlib import Path

ru_path = Path('locales/ru.json')
zh_path = Path('locales/zh.json')

with open(ru_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

def flatten(d, parent=''):
    items = {}
    for k, v in d.items():
        key = f"{parent}.{k}" if parent else k
        if isinstance(v, dict):
            items.update(flatten(v, key))
        else:
            items[key] = v
    return items

def unflatten(d):
    result = {}
    for key, value in d.items():
        parts = key.split('.')
        target = result
        for part in parts[:-1]:
            if part not in target:
                target[part] = {}
            target = target[part]
        target[parts[-1]] = value
    return result

flat = flatten(data)

# Translation map: key pattern -> Chinese translation
# Use dot-notation keys
translations = {
    "meta.siteName": "超级眼睛",
    "meta.siteDesc": "关于眼睛健康的互动漫画",
    "nav.about": "关于漫画",
    "nav.features": "特点",
    "nav.games": "游戏",
    "nav.chapters": "章节",
    "nav.characters": "英雄",
    "nav.parents": "给家长",
    "nav.blog": "博客",
    "nav.start": "▶ 开始",
    "nav.menu": "菜单",
    "nav.close": "关闭",
    "nav.home": "首页",
    "nav.checklist": "检查清单",
    "nav.settings": "设置",
    "nav.profile": "个人资料",
    "hero.badge": "✨ 新章节已上线",
    "hero.title": "超级眼睛",
    "hero.subtitle": "关于眼睛健康的互动漫画。与女超人一起拯救维迪亚尔星球！",
    "hero.ctaPrimary": "▶ 开始冒险",
    "hero.ctaSecondary": "了解更多",
    "hero.scroll": "向下滚动",
    "about.title": "关于漫画",
    "about.subtitle": "在眼睛健康的魔法世界里，视力是最强的超能力",
    "features.title": "特点",
    "features.subtitle": "是什么让《超级眼睛》成为儿童独特项目",
    "features.comic.title": "互动漫画",
    "features.comic.desc": "每一帧都是带对话、配音和视频插入的全屏面板。像刷故事一样滑动！",
    "features.games.title": "迷你游戏",
    "features.games.desc": "与英雄一起训练眼睛：跑酷、体操、眨眼和与懒惰魔王战斗！",
    "features.voice.title": "配音",
    "features.voice.desc": "每帧专业的音频旁白。像听广播剧一样听故事！",
    "features.video.title": "视频",
    "features.video.desc": "AI生成的视频片段让漫画帧栩栩如生，沉浸其中。",
    "gamesSection.title": "迷你游戏",
    "gamesSection.subtitle": "边玩边训练眼睛——每个游戏培养有用技能",
    "gamesSection.runner.title": "追赶像素精灵",
    "gamesSection.runner.desc": "跑、跳、收集奖励。训练快速反应和注意力集中。",
    "gamesSection.gym.title": "与懒惰魔王战斗",
    "gamesSection.gym.desc": "使用三种眼睛超级攻击：激光、瞄准和眼泪。击败魔王！",
    "gamesSection.blink.title": "眼睛体操",
    "gamesSection.blink.desc": "眨眼、眯眼、睁大眼睛。强化眼部肌肉。",
    "gamesSection.tracker.title": "跟随小球",
    "gamesSection.tracker.desc": "用目光跟随移动的小球。培养眼睛平滑运动。",
    "gamesSection.play": "▶ 玩",
    "gamesSection.chooseGame": "🎮 选择游戏",
    "gamesSection.backToList": "← 返回列表",
    "episodes.title": "章节",
    "episodes.subtitle": "选择章节，沉浸于故事",
    "episodes.read": "▶ 阅读",
    "episodes.locked": "🔒",
    "episodes.ep1.num": "第一章",
    "episodes.ep1.name": "女英雄诞生",
    "episodes.ep2.num": "第二章",
    "episodes.ep2.name": "我是谁？",
    "episodes.ep3.num": "第三章",
    "episodes.ep3.name": "伟大战斗",
    "characters.title": "英雄",
    "characters.subtitle": "认识漫画的主要角色",
    "characters.superglazka.name": "超级眼睛",
    "characters.superglazka.role": "女主角",
    "characters.vanya.name": "万尼亚",
    "characters.vanya.role": "忠实朋友",
    "characters.wiseCrystal.name": "智慧水晶",
    "characters.wiseCrystal.role": "维迪亚尔统治者",
    "characters.lenivus.name": "懒惰魔王",
    "characters.lenivus.role": "主要反派",
    "profileLanding.title": "🎮 你的游戏档案",
    "profileLanding.subtitle": "保存进度，收集金币，与朋友竞争",
    "profileLanding.guestTitle": "加入团队！",
    "profileLanding.guestSub": "注册以保存进度、获得胜利奖励并参加比赛。",
    "profileLanding.nicknamePlaceholder": "想个昵称",
    "profileLanding.play": "🚀 玩！",
    "profileLanding.login": "🔑 登录",
    "profileLanding.haveAccount": "已有账号？登录",
    "profileLanding.noAccount": "没有账号？快速开始",
    "profileLanding.coins": "🪙",
    "profileLanding.notPlayed": "尚未玩过",
    "profileLanding.playedTimes": "玩过：{{count}} 次",
    "profileLanding.bestScore": "🏆 {{score}}",
    "cta.title": "准备好冒险了吗？",
    "cta.subtitle": "立即开始阅读漫画",
    "cta.button": "▶ 开始阅读",
    "footer.text": "用心守护儿童视力 ❤️ · 超级眼睛 · 2025",
    "cookieBanner.text": "我们使用 localStorage 保存进度和设置。",
    "cookieBanner.privacy": "隐私政策",
    "cookieBanner.accept": "接受",
    "app.back": "返回",
    "app.settings": "设置",
    "app.profile": "个人资料",
    "app.cinema": "影院模式",
    "app.faq": "帮助",
    "app.continueReading": "继续阅读",
    "app.newChapter": "距离新章节",
    "app.soon": "即将推出！",
    "app.books": "书籍",
    "app.chaptersTab": "章节",
    "app.framesTab": "帧",
    "app.uploadTab": "上传",
    "app.narrator": "旁白",
    "app.subtitles": "字幕",
    "app.fontSize": "字体大小",
    "app.highContrast": "高对比度",
    "app.reduceMotion": "减少动画",
    "app.textSize": "文字大小",
    "app.darkTheme": "深色主题",
    "app.bgMusic": "背景音乐",
    "app.volume": "音量",
    "app.audio": "音频",
    "app.accessibility": "无障碍",
    "app.interface": "界面",
    "app.continueAdventure": "继续冒险",
    "app.continue": "继续",
    "app.nextChapterSoon": "距离新章节",
    "app.comingSoon": "即将推出！",
    "app.showSubtitles": "显示字幕",
    "app.subtitleFontSize": "字幕字体大小",
    "app.help": "❓ 帮助",
    "app.showFullText": "显示全文",
    "app.miniGames": "🎮 迷你游戏",
    "app.miniGame": "迷你游戏！",
    "app.tapToPlay": "点击开始游戏",
    "app.play": "玩",
    "app.next": "下一页 ▶",
    "app.getReady": "准备好接受挑战...",
    "app.playGame": "玩！🚀",
    "app.fight": "战斗！🚀",
    "app.skip": "跳过 ▸",
    "app.great": "太棒了！",
    "app.youDidIt": "你做到了！\n漫画后续...",
    "app.greatJob": "🎉 干得好！",
    "app.wellDone": "干得好！",
    "app.nextFrame": "下一帧...",
    "app.chapters": "📖 章节",
    "app.account": "🔐 账号",
    "app.notifications": "🔔 通知",
    "app.yourEmail": "你的邮箱",
    "app.subscribe": "订阅新章节",
    "brand.subtitle": "游戏童话",
    "time.days": "天",
    "time.hours": "小时",
    "time.minutes": "分钟",
    "time.seconds": "秒",
    "faq.controls.question": "如何操作？",
    "faq.controls.answer": "在电脑上：使用上下箭头或空格键切换到下一帧。Esc键隐藏/显示界面。",
    "faq.controls.answer2": "在手机上：向上/向下滑动切换帧。点击屏幕暂停视频。",
    "faq.sound.question": "如果声音不工作怎么办？",
    "faq.sound.answer": "1. 检查设置中是否启用了所需的音频轨道。2. 在 iOS 上，声音仅在用户首次触摸屏幕后才会打开——这是 Safari 的限制。3. 检查设备音量以及是否开启了静音模式。4. 重新加载页面——有时浏览器会阻止自动播放。",
    "faq.coins.question": "如何赚取金币？",
    "faq.coins.answer": "金币在完成帧和迷你游戏后发放。游戏结果越好（星星越多），金币越多。还可以通过重复通关章节获得奖励金币。",
    "faq.locked.question": "为什么章节被锁定？",
    "faq.locked.answer": "章节依次开放。要解锁下一章，需要看完前一章。进度自动保存。",
    "faq.subtitles.question": "如何开启字幕？",
    "faq.subtitles.answer": "打开设置 → 「字幕」部分 → 切换开关。还可以选择字体大小：小、中或大。",
    "faq.theme.question": "如何更换主题？",
    "faq.theme.answer": "在设置中 → 「界面」部分 → 「深色主题」开关。选择会保存并在两个页面上生效。",
    "games.runner.title": "追赶像素精灵",
    "games.runner.start": "开始",
    "games.runner.jump": "跳！",
    "games.runner.gameOver": "游戏结束",
    "games.runner.win": "胜利！",
    "games.runner.stats": "统计",
    "games.runner.continue": "继续",
    "games.runner.intro": "帮助超级眼睛在桌子上抓住像素精灵！躲避餐具。",
    "games.runner.completed": "🏃 追赶完成！",
    "games.gym.title": "万尼亚对抗懒惰魔王！",
    "games.gym.phaseLaser": "第一阶段：激光",
    "games.gym.phaseAim": "第二阶段：瞄准",
    "games.gym.phaseTears": "第三阶段：眼泪",
    "games.gym.charge": "充电！",
    "games.gym.release": "释放！",
    "games.gym.aim": "瞄准！",
    "games.gym.tap": "按！",
    "games.gym.win": "胜利！",
    "games.gym.stats": "统计",
    "games.gym.continue": "继续",
    "games.gym.intro": "帮助万尼亚击败懒惰魔王！使用三种超级攻击：激光、瞄准和眼泪。",
    "games.gym.bossName": "👁️ 懒惰魔王",
    "games.gym.rays": "光线",
    "games.gym.ray": "⚡ 太阳光线",
    "games.gym.scope": "🎯 精确瞄准",
    "games.gym.tears": "💧 泪之瀑布",
    "games.blink.title": "眼睛体操",
    "games.blink.round1": "第一轮：眨眼",
    "games.blink.round2": "第二轮：眯眼",
    "games.blink.round3": "第三轮：睁大",
    "games.blink.blink": "眨眼！",
    "games.blink.squeeze": "按！",
    "games.blink.wide": "睁大！",
    "games.blink.win": "太棒了！",
    "games.blink.stats": "统计",
    "games.blink.continue": "继续",
    "games.blink.round": "轮",
    "games.blink.time": "时间",
    "games.blink.hint": "点击屏幕眨眼！",
    "games.tracker.title": "跟随小球",
    "games.tracker.follow": "用目光跟随！",
    "games.tracker.win": "完成！",
    "games.tracker.stats": "统计",
    "games.tracker.continue": "继续",
    "games.tracker.phase": "阶段",
    "games.tracker.hint": "用眼睛跟随小球 👀",
    "games.stats.lives": "❤️ 生命",
    "games.stats.livesLeft": "剩余生命：",
    "games.stats.bonuses": "💎 奖励",
    "games.stats.collected": "已收集：",
    "games.stats.result": "🎯 结果",
    "games.stats.distance": "距离：",
    "games.stats.status": "状态：",
    "games.stats.victory": "胜利！",
    "games.stats.rating": "🏆 评分：⭐⭐⭐",
    "games.stats.hits": "命中：",
    "games.stats.accuracy": "准确度：",
    "games.stats.avgTime": "平均瞄准时间：",
    "games.stats.waterfalls": "瀑布：",
    "games.stats.totalBlinks": "总眨眼数：",
    "games.stats.totalScore": "🏆 总分：0",
    "profile.title": "个人资料",
    "profile.nickname": "昵称",
    "profile.coins": "金币",
    "profile.episodes": "📖 章节",
    "profile.games": "🎮 迷你游戏",
    "profile.achievements": "🏆 成就",
    "profile.account": "🔐 账号",
    "profile.guestText": "你以访客身份游戏。进度会保存，但金币暂时无法使用。",
    "profile.createAccount": "🔐 创建完整账号",
    "profile.loginBtn": "🔑 已有账号？登录",
    "profile.enterLogin": "🔑 登录 / 注册",
    "profile.email": "邮箱",
    "profile.logout": "🚪 退出",
    "profile.notifications": "🔔 通知",
    "profile.subscribePlaceholder": "你的邮箱",
    "profile.subscribeBtn": "订阅新章节",
    "auth.login": "登录",
    "auth.register": "注册",
    "auth.guest": "访客",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.nickname": "昵称",
    "auth.enter": "登录",
    "auth.create": "创建",
    "auth.quickStart": "快速开始",
    "auth.fullAccount": "完整账号",
    "auth.or": "或",
    "auth.loginError": "邮箱或密码错误",
    "auth.registerError": "注册错误",
    "auth.emptyFields": "请填写所有字段！",
    "auth.enterNickname": "请输入昵称！",
    "auth.enterEmailPassword": "请输入邮箱和密码！",
    "auth.joinTeam": "🌟 加入团队！",
    "auth.joinBenefits": "注册以：保存进度、获得胜利奖励、开启下一系列漫画、参加比赛",
    "auth.joinBenefitsGym": "注册以：保存进度、获得训练奖励、开启下一系列漫画、参加比赛",
    "auth.nicknamePlaceholder": "想个昵称",
    "auth.parentEmailPlaceholder": "家长邮箱",
    "auth.parentsAllowed": "家长允许游戏",
    "auth.registerBtn": "🚀 注册",
    "auth.skipRegistration": "继续无需注册 →",
    "auth.guestDesc": "输入昵称开始游戏。进度会保存，但金币暂时无法使用。",
    "auth.yourNickname": "你的昵称",
    "auth.play": "🚀 玩！",
    "auth.parentEmail": "家长邮箱",
    "auth.phoneOptional": "电话（可选）",
    "auth.passwordMin6": "密码（至少6个字符）",
    "auth.haveAccount": "已有账号？",
    "auth.login": "登录",
    "auth.loginBtn": "🔑 登录",
    "auth.noAccount": "没有账号？",
    "auth.register": "注册",
    "achievements.unlocked": "🏆 成就解锁！",
    "achievements.title": "成就",
    "achievements.first_step": "第一步",
    "achievements.first_step_desc": "观看第一帧",
    "achievements.pixel_hunter": "像素猎人",
    "achievements.pixel_hunter_desc": "完成「追赶像素精灵」",
    "achievements.eye_gymnast": "眼睛体操运动员",
    "achievements.eye_gymnast_desc": "完成体操3次",
    "achievements.blinker": "眨眼者",
    "achievements.blinker_desc": "完成「眨眼游戏」",
    "achievements.tracker": "追踪者",
    "achievements.tracker_desc": "完成「跟随小球」",
    "achievements.bookworm": "书虫",
    "achievements.bookworm_desc": "完成一章",
    "achievements.librarian": "图书馆员",
    "achievements.librarian_desc": "完成所有章节",
    "achievements.rich": "富翁",
    "achievements.rich_desc": "积累500金币",
    "daily.title": "🎁 每日奖励",
    "daily.subtitle": "每天登录领取金币！",
    "daily.streak": "🔥 连续：{{count}} 天",
    "daily.day": "天",
    "daily.claim": "领取 {{amount}} 🪙",
    "daily.claimed": "✅ 你今天已经领取了奖励。明天再来！",
    "daily.received": "🎉 获得 {{amount}} 金币！连续：{{streak}}",
    "parents.title": "给家长",
    "parents.subtitle": "关于孩子眼睛健康的一切重要信息",
    "parents.benefits.title": "🎯 项目益处",
    "parents.benefits.attention": "注意力发展",
    "parents.benefits.attentionDesc": "游戏练习训练孩子的随意注意力。",
    "parents.benefits.hygiene": "视力卫生",
    "parents.benefits.hygieneDesc": "漫画以有趣的方式向孩子们介绍眼睛健康规则。",
    "parents.benefits.fatigue": "预防疲劳",
    "parents.benefits.fatigueDesc": "练习缓解屏幕使用后的紧张。",
    "parents.benefits.muscles": "强化肌肉",
    "parents.benefits.musclesDesc": "调节练习强化眼部肌肉。",
    "parents.time.title": "⏱️ 时间建议",
    "parents.time.chapterTime": "一章——10-15分钟。",
    "parents.time.break": "章节后休息20分钟。",
    "parents.time.maxChapters": "每天不超过2章。",
    "parents.time.lighting": "良好的照明。",
    "parents.explain.title": "💬 如何向孩子解释",
    "parents.explain.p1": "「超级眼睛教你的眼睛像超级英雄一样强大！」",
    "parents.explain.p2": "「练习帮助眼睛在平板和手机后休息。」",
    "parents.explain.p3": "「每次你训练，你的眼睛变得更快更聪明。」",
    "parents.explain.p4": "「这就像一个健身房，但是给眼睛的——练习得越多，看得越清楚。」",
    "parents.checklist.title": "📋 家长检查清单",
    "parents.checklist.distance": "孩子坐在屏幕前不少于30厘米。",
    "parents.checklist.rule202020": "20分钟屏幕后——20秒休息。",
    "parents.checklist.noGlare": "房间光线充足，没有眩光。",
    "parents.checklist.blink": "孩子在做练习时眨眼。",
    "parents.checklist.noScreenBeforeBed": "睡前1小时最少屏幕时间。",
    "parents.contact.title": "📧 反馈",
    "parents.contact.text": "有问题、建议或意见？我们总是很高兴听到您的想法。",
    "parents.contact.email": "写信至 hello@superglazka.ru",
    "parents.contact.socials": "或在社交媒体上找到我们：",
    "blog.title": "超级眼睛博客",
    "blog.subtitle": "关于儿童眼睛健康的有用建议",
    "blog.loading": "加载文章...",
    "blog.empty": "暂无文章。稍后再来！",
    "blog.error": "无法加载文章",
    "checklistPage.title": "10条眼睛健康规则",
    "checklistPage.subtitle": "家长检查清单 · 打印并贴在冰箱上",
    "checklistPage.progress": "已完成 {{done}} / {{total}}",
    "checklistPage.dailyRules": "📋 每日规则",
    "checklistPage.rule202020": "20-20-20规则。每20分钟屏幕时间——20秒休息，看向6米外。",
    "checklistPage.distance": "与屏幕的距离。显示器至少50-60厘米，平板30厘米。",
    "checklistPage.lighting": "良好的照明。屏幕上没有眩光，房间光线充足。",
    "checklistPage.blink": "多眨眼！提醒孩子在使用屏幕时眨眼。",
    "checklistPage.noScreenBeforeBed": "睡前1小时不看屏幕。蓝光干扰褪黑素分泌。",
    "checklistPage.nutrition": "🥗 营养与生活方式",
    "checklistPage.vitaminA": "维生素A。胡萝卜、南瓜、杏、肝脏——每天食用。",
    "checklistPage.omega3": "Omega-3。鱼、亚麻籽、核桃——保护视网膜。",
    "checklistPage.walks": "户外散步。每天至少1小时——眼睛的自然训练。",
    "checklistPage.prevention": "🏥 预防",
    "checklistPage.doctor": "眼科检查。即使没有投诉，每年1次。",
    "checklistPage.noRub": "不要用脏手揉眼睛。感染是视力问题的常见原因。",
    "checklistPage.print": "🖨️ 打印检查清单",
    "checklistPage.reset": "↺ 重置进度",
    "privacy.title": "隐私政策",
    "privacy.updated": "更新日期：2026年5月21日",
    "privacy.p1": "1. 收集哪些数据",
    "privacy.p2": "2. 为什么收集数据",
    "privacy.p3": "3. 谁可以访问",
    "privacy.p4": "4. 存储与安全",
    "privacy.p5": "5. 如何删除数据",
    "privacy.p6": "6. Cookie 和 localStorage",
    "privacy.p7": "7. 儿童安全",
    "privacy.p8": "8. 政策变更",
    "privacy.p9": "9. 联系方式",
    "admin.login": "管理员登录",
    "admin.apiKey": "API密钥",
    "admin.enter": "登录",
    "admin.logout": "退出",
    "admin.episodes": "章节",
    "admin.frames": "帧",
    "admin.upload": "上传",
    "admin.newEpisode": "新章节",
    "admin.search": "搜索",
    "admin.title": "标题",
    "admin.description": "描述",
    "admin.order": "顺序",
    "admin.published": "已发布",
    "admin.save": "保存",
    "admin.delete": "删除",
    "admin.duplicate": "复制",
    "admin.narration": "旁白",
    "admin.dialogue": "对话",
    "admin.background": "背景",
    "admin.mood": "情绪",
    "admin.game": "游戏",
    "admin.preview": "预览",
    "admin.success": "成功",
    "admin.error": "错误",
}

for key, zh_val in translations.items():
    if key in flat:
        flat[key] = zh_val
    # else: key may not exist in ru.json (newer keys) — skip

# For any remaining keys, leave as-is (they stay in Russian as fallback works via ru.json)
# Actually, to make fallback work cleanly, set empty string for untranslated keys
# so t() will fall through to ru.json
for key in flat:
    if key not in translations:
        flat[key] = ""

data = unflatten(flat)

with open(zh_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Created {zh_path} with {len(translations)} translated keys")
